// QMC.cpp
// Implementation of quasi-Monte-Carlo low-discrepancy sequences.
// See QMC.h for the public interface and rationale.

#include "QMC.h"

#include <cmath>
#include <cstdint>

// First 16 primes, used as bases for the Halton sequence dimensions.
static const uint32_t kPrimes[16] = {2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53};
static const int kNumPrimes = 16;

// van der Corput radical inverse in an arbitrary base.
// We repeatedly extract the least significant digit of "index" in the given
// base and accumulate it into ever smaller fractional places. The result is
// the reflection of "index" about the radix point.
float radicalInverse(uint32_t base, uint32_t index) {
	if (base < 2) {
		base = 2; // guard against degenerate bases
	}
	float result = 0.0f;
	float invBase = 1.0f / static_cast<float>(base);
	float fraction = invBase;
	while (index > 0) {
		uint32_t digit = index % base;
		result += static_cast<float>(digit) * fraction;
		index /= base;
		fraction *= invBase;
	}
	return result;
}

// Halton sequence: each dimension uses a different prime base.
float halton(int dimension, uint32_t index) {
	if (dimension < 0) {
		dimension = 0;
	}
	// Fall back gracefully for dimensions beyond the table: reuse the last
	// known prime rather than reading out of bounds. Correlation increases
	// for very high dimensions, but the call stays valid.
	int d = (dimension < kNumPrimes) ? dimension : (kNumPrimes - 1);
	return radicalInverse(kPrimes[d], index);
}

// Hammersley 2D point. The first coordinate is a simple even split of the
// [0, 1) interval by sample index; the second is the base-2 radical inverse.
glm::vec2 hammersley(uint32_t index, uint32_t count) {
	float x = 0.0f;
	if (count > 0) {
		x = static_cast<float>(index) / static_cast<float>(count);
	}
	float y = radicalInverse(2, index);
	return glm::vec2(x, y);
}

// Sobol direction numbers for the first two dimensions (base 2).
// Dimension 0 is the classic van der Corput / bit-reversal pattern.
// Dimension 1 uses the direction numbers generated by the Sobol primitive
// polynomial x + 1, which produces the well known Gray-code style sequence.
// Both are precomputed as 32 direction vectors.

// Build the 32 direction numbers for Sobol dimension 0 (v[i] = 1 << (31 - i)).
static void sobolDirections0(uint32_t v[32]) {
	for (int i = 0; i < 32; i++) {
		v[i] = 1u << (31 - i);
	}
}

// Build the 32 direction numbers for Sobol dimension 1.
// For the polynomial with a single recurrence term, each direction number is
// obtained from the previous one by XOR-ing in its own shifted copy. This is
// the standard construction that yields the second Sobol dimension.
static void sobolDirections1(uint32_t v[32]) {
	v[0] = 1u << 31;
	for (int i = 1; i < 32; i++) {
		v[i] = v[i - 1] ^ (v[i - 1] >> 1);
	}
}

// Evaluate a base-2 Sobol coordinate from a set of direction numbers.
// We walk the set bits of "index" (Gray-code / direct summation form) and XOR
// in the matching direction number, then optionally XOR a scramble seed.
static float sobolEval(uint32_t index, const uint32_t v[32], uint32_t scramble) {
	uint32_t result = scramble;
	uint32_t i = index;
	int bit = 0;
	while (i > 0) {
		if (i & 1u) {
			result ^= v[bit];
		}
		i >>= 1;
		bit++;
	}
	// Scale the 32-bit integer into [0, 1). The factor 2^-32 keeps the value
	// strictly below 1.0 for all inputs.
	return static_cast<float>(result) * (1.0f / 4294967296.0f);
}

float sobol1D(uint32_t index, uint32_t scramble) {
	uint32_t v[32];
	sobolDirections0(v);
	return sobolEval(index, v, scramble);
}

glm::vec2 sobol2D(uint32_t index, uint32_t scramble) {
	uint32_t v0[32];
	uint32_t v1[32];
	sobolDirections0(v0);
	sobolDirections1(v1);
	// Derive an independent scramble for the second dimension so the two
	// coordinates are not correlated. A cheap integer hash of the seed works
	// well enough for decorrelation here.
	uint32_t scramble2 = scramble * 0x9E3779B1u + 0x85EBCA6Bu;
	float x = sobolEval(index, v0, scramble);
	float y = sobolEval(index, v1, scramble2);
	return glm::vec2(x, y);
}

// Concentric (Shirley) mapping from the unit square to the unit disk.
// The naive polar mapping compresses samples toward the centre; the
// concentric mapping preserves relative area and therefore stratification.
glm::vec2 uniformDisk(glm::vec2 u) {
	// Map [0, 1)^2 to [-1, 1)^2.
	float ox = 2.0f * u.x - 1.0f;
	float oy = 2.0f * u.y - 1.0f;

	if (ox == 0.0f && oy == 0.0f) {
		return glm::vec2(0.0f, 0.0f);
	}

	float r;
	float theta;
	const float pi = 3.14159265358979323846f;
	if (std::fabs(ox) > std::fabs(oy)) {
		r = ox;
		theta = (pi / 4.0f) * (oy / ox);
	} else {
		r = oy;
		theta = (pi / 2.0f) - (pi / 4.0f) * (ox / oy);
	}
	return glm::vec2(r * std::cos(theta), r * std::sin(theta));
}

// Cosine-weighted hemisphere sampling about an arbitrary normal.
// We first sample a disk, lift it to the hemisphere (Malley's method), then
// rotate the local (tangent-space) direction into world space using an
// orthonormal basis built from the normal.
glm::vec3 cosineHemisphere(glm::vec2 u, const glm::vec3 &normal) {
	// Malley's method: a cosine-weighted hemisphere is a uniform disk sample
	// projected up onto the hemisphere.
	glm::vec2 d = uniformDisk(u);
	float z2 = 1.0f - d.x * d.x - d.y * d.y;
	if (z2 < 0.0f) {
		z2 = 0.0f; // guard against tiny negative values from rounding
	}
	float z = std::sqrt(z2);
	glm::vec3 local(d.x, d.y, z);

	// Build an orthonormal basis (tangent, bitangent, normal). We pick a
	// helper axis that is not parallel to the normal to avoid a degenerate
	// cross product.
	glm::vec3 n = glm::normalize(normal);
	glm::vec3 helper = (std::fabs(n.x) > 0.9f) ? glm::vec3(0.0f, 1.0f, 0.0f) : glm::vec3(1.0f, 0.0f, 0.0f);
	glm::vec3 tangent = glm::normalize(glm::cross(helper, n));
	glm::vec3 bitangent = glm::cross(n, tangent);

	// Transform the local hemisphere direction into world space.
	return glm::normalize(local.x * tangent + local.y * bitangent + local.z * n);
}
