name: Publish npm package

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # required for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Emscripten
        uses: mymindstorm/setup-emsdk@v14

      - name: Build WebAssembly module
        run: bash build.sh
        working-directory: bindings/wasm

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: Publish to npm
        run: npm publish --provenance --access public
        working-directory: bindings/wasm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
